sonar.projectKey=PowerDNS-Admin-PHP
sonar.projectName=PowerDNS-Admin-PHP
sonar.sources=app,public,views
sonar.exclusions=public/assets/vendor/**,node_modules/**

# Allow snake_case for procedural PHP functions
sonar.php.customrules.php:S100.format=^[a-z][a-zA-Z0-9_]*$
